
name: Build

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - 'main'
      - '*'
    tags:        
      - '*'

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  BuildAndPushDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Get IMAGE_TAG
        id: get-image-tag
        run: |
          export SHORT_SHA=$( echo ${{github.sha}} | cut -c 1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$( echo "${BRANCH_NAME}-${SHORT_SHA}")">> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

#      - name: Build, tag, and push image to Amazon ECR
#        run: |
#          echo "jktu/deye-mqtt:$IMAGE_TAG"
#          docker buildx build --platform=linux/arm64 -t jktu/deye-mqtt:$IMAGE_TAG .
#          docker push jktu/deye-mqtt:$IMAGE_TAG
#          docker tag jktu/deye-mqtt:$IMAGE_TAG jktu/deye-mqtt:latest
#          docker push jktu/deye-mqtt:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jktu/deye-mqtt:latest